baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Gallery'
theme = ["gallery"]
copyright = "©BigBigMeng"
defaultContentLanguage = "zh-cn"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
timeout = "120s"


[params]
  defaultTheme = "light"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "user@example.com"
    name = "Your Name"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.113.0"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery"

[menu]
  [[menu.footer]]
    name = "BACK2BLOG"
    url = "https://blog.bigbigmeng.online"
    weight = 3

[services]
  [services.rss]
    limit = 100
